attributes/default.rb, recipes/default.rb, recipes/flower.rb, recipes/install.rb, recipes/kerberos.rb, recipes/packages.rb, recipes/scheduler.rb, recipes/services.rb, recipes/webserver.rb, recipes/worker.rb, templates/default/airflow_runner.sh.erb, templates/default/init_system/systemd/airflow-flower.service.erb, templates/default/init_system/systemd/airflow-kerberos.service.erb, templates/default/init_system/systemd/airflow-scheduler.service.erb, templates/default/init_system/systemd/airflow-webserver.service.erb, templates/default/init_system/systemd/airflow-worker.service.erb
[airflow_conda_env]  systemd should use airflow conda env
[airflow_conda_env]  Install packages in default phase
[airflow_conda_env]  Fix typo
[airflow_conda_env]  Fixes
[airflow_conda_env]  Fix systemd units to start airflow from conda environment
=> [airflow_conda_env]  Create Airflow anaconda environment

recipes/directories.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-949
=> Create top level Hops dir if it does not exist

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-955
=> [HOPSWORKS-955-amend]  Remove obsolete configuration property for superuser

Karamelfile, recipes/scheduler.rb, recipes/user.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-953
=> [HOPSWORKS-953]  Increase service fail threshold for scheduler

attributes/default.rb, metadata.rb, templates/default/init_system/airflow-env.erb, templates/default/init_system/systemd/airflow-scheduler.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-975
=> [HOPSWORKS-975]  Tweak airflow scheduler configuration

files/default/create_db_idx_proc.sql, files/default/hopsworks_plugin/hooks/hopsworks_hook.py, files/default/hopsworks_plugin/operators/__init__.py, files/default/hopsworks_plugin/operators/hopsworks_operator.py, files/default/hopsworks_plugin/sensors/hopsworks_sensor.py, metadata.rb, recipes/db.rb, recipes/default.rb, templates/default/airflow_runner.sh.erb, templates/default/init_system/airflow-env.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-966
Creates a wrapper around SqoopOperator which performs all the necessary operations to integrate it with Hopsworks and Airflow.
Also, tweak some configuration parameters for Airflow scheduler.
=> [HOPSWORKS-966] Apache Sqoop integration with Hopsworks/Airflow

attributes/default.rb, attributes/packages.rb, recipes/packages.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-926
=> [HOPSWORKS-926] Remove broken Airflow dependencies and fix platform family

files/default/hopsworks_plugin/hooks/hopsworks_hook.py, files/default/hopsworks_plugin/operators/__init__.py, files/default/hopsworks_plugin/operators/hopsworks_operator.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1110
[HOPSWORKS-1110] Update, start and stop a model serving instance
[HOPSWORKS-1110] New API
[HOPSWORKS-1110] Add flag to make Launch operator blocking
=> [HOPSWORKS-1110] Model serving operator and blocking job launch operator

recipes/scheduler.rb, recipes/sqoop.rb, recipes/webserver.rb, templates/default/init_system/systemd/airflow-scheduler.service.erb, templates/default/init_system/systemd/airflow-webserver.service.erb, templates/default/sqoop.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091
=> [HOPSWORKS-1091] Add Systemd unit file deps

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1178
=> [HOPSWORKS-1178] Set Airflow to use system timezone

templates/default/init_system/airflow-env.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1235
=> [HOPSWORKS-1235] Log Gunicorn in warning

files/default/hopsworks_plugin/operators/hopsworks_operator.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1252
=> [HOPSWORKS-1252] Fail Airflow task too if Hopsworks Job failed

files/default/hopsworks_plugin/hooks/hopsworks_hook.py, files/default/hopsworks_plugin/operators/hopsworks_operator.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1286
=> [HOPSWORKS-1286] Authenticate using API key if possible

files/default/hopsworks_plugin/hooks/hopsworks_hook.py, files/default/hopsworks_plugin/operators/__init__.py, files/default/hopsworks_plugin/operators/hopsworks_operator.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1312
Airflow operator to fetch Feature store data validation result and fail the DAG if validation was unsuccessful
=> [HOPSWORKS-1312] Airflow operator to fetch Feature store validation result

Berksfile, metadata.rb, recipes/db.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679
=> [HOPSWORKS-1679] pin version of java in Berksfile

templates/default/consul/airflow-consul.hcl.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1718
=> [HOPSWORKS-1718] Register service with passing health state

recipes/user.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1694
=> [HOPSWORKS-1694] run user code in docker

attributes/default.rb, recipes/db.rb, recipes/sqoop.rb, templates/default/sqoop-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1825
=> [HOPSWORKS-1825] Connect to local mysqld

recipes/sqoop.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1872
=> [HOPSWORKS-1872] Fix wrong attribute

recipes/sqoop.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1904
=> [HOPSWORKS-1904] Remove sqoop user from privileged certs group

files/default/hopsworks_plugin/sensors/hopsworks_sensor.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1920
=> [HOPSWORKS-1920] Airflow Sensors pass API key to connection hook

files/default/hopsworks_plugin/sensors/hopsworks_sensor.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1920
=> [HOPSWORKS-1920] Airflow Sensors pass API key to connection hook (#57)

recipes/sqoop.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1923
=> [HOPSWORKS-1923] Remove user from certs group

attributes/default.rb, recipes/packages.rb, recipes/webserver.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2162
=> [HOPSWORKS-2162] Install airflow-exporter from pip and set constraint for airflow package

attributes/default.rb, recipes/packages.rb, recipes/webserver.rb
* [HOPSWORKS-2162] Install airflow-exporter from pip and set constraint for airflow package
* [HOPSWORKS-2162] Export env variables for correct installation of mysqlclient
[HOPSWORKS-2162]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2162
[HOPSWORKS-2162]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2162
=> [HOPSWORKS-2162] Install airflow-exporter from pip and set constraint for airflow package (#62)

attributes/default.rb, recipes/default.rb, recipes/directories.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Store airflow user data to data volume

recipes/packages.rb
Fixes setuptools > 58.0 problem with airflow
=> [HOPSWORKS-2737] pre-install Flask-OpenID==1.3.0

recipes/db.rb, recipes/packages.rb
Reverts logicalclocks/airflow-chef#82
=> Revert "[HOPSWORKS-2808] Change user home (#81)"

recipes/directories.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Delete old secrets directory even if it is empty

recipes/packages.rb
https://hopsworks.atlassian.net/browse/CLOUD-357
=> [CLOUD-357] Update mariadb repo

attributes/default.rb, files/default/log_config.py, recipes/config.rb, recipes/db.rb, templates/default/airflow-scheduler.service.erb, templates/default/airflow-webserver.service.erb
https://hopsworks.atlassian.net/browse/HWORKS-651
=> [HWORKS-651] Configure Airflow to log in a file instead of stdout

attributes/default.rb, files/default/log_config.py, recipes/config.rb, recipes/db.rb, templates/default/airflow-scheduler.service.erb, templates/default/airflow-webserver.service.erb
* [HWORKS-651] Configure Airflow to log in a file instead of stdout
* [HWORKS-651] Add required volumes to db initialization
[HWORKS-651]: https://hopsworks.atlassian.net/browse/HWORKS-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HWORKS-651]: https://hopsworks.atlassian.net/browse/HWORKS-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HWORKS-651] Configure Airflow to log in a file instead of stdout (#95)
